export declare function decamelize(str: string): string;
export declare function capitalize(str: string): string;
export declare function dasherize(str: string): string;
export declare function camelize(str: string): string;
export declare function classify(str: string): string;
export declare function underscore(str: string): string;
export declare function pascalize(str: string): string;
export declare function preserveCaseSafe(name: string): string;
export declare function camelizeSafe(name: string): string;
