name: Pull request

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.17.3'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: |
          yarn test:lib:protoc-gen-worker:generate-grpc-worker
          yarn test:lib:protoc-gen-worker:generate-grpc-web
          yarn test:lib:protoc-gen-worker
      - name: Lint
        run: yarn lint
