name: Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: |
          yarn test:lib:protoc-gen-worker:generate-grpc-worker
          yarn test:lib:protoc-gen-worker:generate-grpc-web
          yarn test:lib:protoc-gen-worker
      - name: Lint
        run: yarn lint
      # - name: Publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn release
